### ISSUE TITLE
About magnification

### ISSUE THREAD

**Issue by ljhOfGithub** [liupei101/DSCA#7]
Your 20x actually is 10x, and 5x autually is 2.5x. See this: https://github.com/mahmoodlab/CLAM/issues/115.
You don't change the custom_downsample in the extract_features_fp.py and patch_size in the create_patches_fp.py.

**Comment by syy-create** [comment]
请问为什么这个20x实际得到的10x啊，如果按照作者所说，level=0，patchsize&stepsize=512，custom_downsample=2得到20x视野。那么在level=0，patchsize&stepsize=1024，custom_downsample=4，得到的不应该是10x背景吗？请问是我那个地方理解错了呀，可以告诉我下吗？非常感谢。

**Comment by ljhOfGithub** [comment]
> 请问为什么这个20x实际得到的10x啊，如果按照作者所说，level=0，patchsize&stepsize=512，custom_downsample=2得到20x视野。那么在level=0，patchsize&stepsize=1024，custom_downsample=4，得到的不应该是10x背景吗？请问是我那个地方理解错了呀，可以告诉我下吗？非常感谢。

我也不理解，我只知道参数这么设置

**Comment by syy-create** [comment]
谢谢你的回复，请问你是如何确定实际缩小的倍率呢？如刚刚所提问题的20x实际为10x，你可以稍微给我些启示吗？或者说参考的资料。&nbsp;


^^^^^^
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月29日(星期三) 晚上9:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liupei101/DSCA] About magnification (Issue #7)





  
请问为什么这个20x实际得到的10x啊，如果按照作者所说，level=0，patchsize&amp;stepsize=512，custom_downsample=2得到20x视野。那么在level=0，patchsize&amp;stepsize=1024，custom_downsample=4，得到的不应该是10x背景吗？请问是我那个地方理解错了呀，可以告诉我下吗？非常感谢。
  
我也不理解，我只知道参数这么设置

**Comment by ljhOfGithub** [comment]
> 谢谢你的回复，请问你是如何确定实际缩小的倍率呢？如刚刚所提问题的20x实际为10x，你可以稍微给我些启示吗？或者说参考的资料。&nbsp; ^^^^^^ ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年11月29日(星期三) 晚上9:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [liupei101/DSCA] About magnification (Issue #7) 请问为什么这个20x实际得到的10x啊，如果按照作者所说，level=0，patchsize&amp;stepsize=512，custom_downsample=2得到20x视野。那么在level=0，patchsize&amp;stepsize=1024，custom_downsample=4，得到的不应该是10x背景吗？请问是我那个地方理解错了呀，可以告诉我下吗？非常感谢。 我也不理解，我只知道参数这么设置 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我在issue找的，没有参考资料

**Comment by syy-create** [comment]
好的谢谢你，我再看看。非常感谢！
&nbsp;


^^^^^^
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月29日(星期三) 晚上9:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liupei101/DSCA] About magnification (Issue #7)





  
谢谢你的回复，请问你是如何确定实际缩小的倍率呢？如刚刚所提问题的20x实际为10x，你可以稍微给我些启示吗？或者说参考的资料。&nbsp; ^^^^^^ @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年11月29日(星期三) 晚上9:03 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [liupei101/DSCA] About magnification (Issue #7) 请问为什么这个20x实际得到的10x啊，如果按照作者所说，level=0，patchsize&amp;stepsize=512，custom_downsample=2得到20x视野。那么在level=0，patchsize&amp;stepsize=1024，custom_downsample=4，得到的不应该是10x背景吗？请问是我那个地方理解错了呀，可以告诉我下吗？非常感谢。 我也不理解，我只知道参数这么设置 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
我在issue找的，没有参考资料
